// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qprxivkkxvjzwcamvpqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwcnhpdmtreHZqendjYW12cHF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNDcxOTQsImV4cCI6MjA2MzcyMzE5NH0.S2S5oYBJwdTaoOtD51olrP14OJYztYYg9Uvr0bQLVDs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);